name: Testing 

env:
 TARGET: bugcrowd.com
 BOUNTY_STRIKE_PATH : strike 
 
on: push

jobs:
 download_others_repo:
  name: testing
  
  runs-on: [ubuntu-latest]
  strategy:
   matrix:
    python-version: [3.8]
    go-version: [1.13.1]
    php-version: [7.4]


  steps:
# Setup python 
   - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v1
     with:
       python-version: ${{ matrix.python-version }}  

# Setup go version
   - name: Setup Go environment
     uses: actions/setup-go@v2.0.3
     with:
      # The Go version to download (if necessary) and use. Supports semver spec and ranges.
      go-version: ${{ matrix.go-version }}
      # Whether to download only stable versions
      # stable: # optional, default is true    

# Setup PHP 7.4 version
   - name : Setup Php 7.4
     uses: shivammathur/setup-php@v2
     with:
      php-version: ${{ matrix.php-version }}     
      
   - name : Checking out own repo
     uses : actions/checkout@v2

# seting up bash profile    
   - name : seting up bash profile
     run : |
      cd ${{ github.workspace }}
      ls -la
      chmod +x *
      cat ~/.bash_profile
      source .bash_profile    

# test bash profile    
   - name : test bash profile
     run : |
      cd ${{ github.workspace }}
      ls -la
      hackertarget  ${{ env.TARGET }}    
   

  #  - name : checkout https://github.com/BountyStrike/Bountystrike-sh
  #    uses : actions/checkout@master
  #    with : 
  #      repository : BountyStrike/Bountystrike-sh
  #      path :  ${{ env.BOUNTY_STRIKE_PATH }}


  #  - name : installing tools
  #    run : |
  #      cd ${{ github.workspace }}/${{ env.BOUNTY_STRIKE_PATH }}
  #      chmod +x *
  #      ./bstrike.sh install  

  #  - name : Run pipeline on ${{ env.TARGET }}
  #    run : |
  #      cd ${{ github.workspace }}/${{ env.BOUNTY_STRIKE_PATH }}
  #      ./bstrike.sh run hackerone hackerone.com   
  

        
