 
name: Testing 

env:
 TARGET: bugcrowd.com 
 
on: push

jobs:
 download_others_repo:
  name: OpenRedireX - Asynchronous Open redirect Fuzzer for Humans
  
  runs-on: [ubuntu-latest]
  strategy:
   matrix:
    python-version: [3.7]
  steps:
   - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v1
     with:
        python-version: ${{ matrix.python-version }}
   - name : checking git version
     run : |
      git --version  
   - name : installing dependencies - aiohttp
     run : |
      pip3 install aiohttp
  #  - name : installing jq
  #    run : |
  #     sudo apt-get install jq
  #     go get -u github.com/tomnomnom/httprobe
   - name: Downloading from https://github.com/devanshbatham/OpenRedireX
     id: step1
     run: |
      git clone https://github.com/devanshbatham/OpenRedireX
      cd OpenRedireX
      python3 -m venv env
      source env/bin/activate
      python3.7 openredirex.py -u "https://${{ env.TARGET }}/?url=FUZZ" -p payloads.txt --keyword FUZZ
   - name : Multiprocessing(Parallel)Subdomain Detect Script
     run : |
      git clone https://github.com/aboul3la/Sublist3r.git
      cd Sublist3r
      sudo pip install -r requirements.txt
      python sublist3r.py -b -d ${{ env.TARGET }}
   #- name : checking output of step1
   #  run : ${{steps.step1.outputs}}
  #  - name: oction-create-issue     
  #    uses: maxkomarychev/oction-create-issue@v0.7.1
  #    id: my_step_id
  #    with:
  #      token: ${{ secrets.GITHUB_TOKEN }}
  #      title: ${{ env.TARGET }}
  #      body:  html body <b>hell0 </b>
  

  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test for public javascript library vulnerabilities 
  #       uses: lirantal/is-website-vulnerable@master
  #       with:
  #         scan-url: ${{ env.TARGET }}
  # zap_scan:
  #   runs-on: ubuntu-latest
  #   name: Scan the webapplication
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: master
  #     - name: ZAP Scan
  #       uses: zaproxy/action-baseline@v0.2.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         docker_name: 'owasp/zap2docker-stable'
  #         target: ${{ env.TARGET }}
  #         rules_file_name: '.zap/rules.tsv'
  #         cmd_options: '-a'
