 
name: Testing 

env:
 TARGET: bugcrowd.com
 BOUNTY_STRIKE_PATH : strike 
 
on: push

jobs:
 download_others_repo:
  name: OpenRedireX - Asynchronous Open redirect Fuzzer for Humans
  
  runs-on: [ubuntu-latest]
  strategy:
   matrix:
    python-version: [3.8]
  steps:
   - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v1
     with:
        python-version: ${{ matrix.python-version }}
   

   - name : checkout https://github.com/BountyStrike/Bountystrike-sh
     uses : action/checkout@v2
     with : 
       repository : BountyStrike/Bountystrike-sh
       path :  ${{ env.BOUNTY_STRIKE_PATH }}


   - name : installing tools
     run : |
       cd ${{ github.workspace }}/${{ env.BOUNTY_STRIKE_PATH }}
       bstrike.sh install  

   - name : Run pipeline on ${{ env.TARGET }}
     run : |
       cd ${{ github.workspace }}/${{ env.BOUNTY_STRIKE_PATH }}
       bstrike.sh run Bugcrowd ${{ env.TARGET }}    
  

  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test for public javascript library vulnerabilities 
  #       uses: lirantal/is-website-vulnerable@master
  #       with:
  #         scan-url: ${{ env.TARGET }}
  # zap_scan:
  #   runs-on: ubuntu-latest
  #   name: Scan the webapplication
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: master
  #     - name: ZAP Scan
  #       uses: zaproxy/action-baseline@v0.2.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         docker_name: 'owasp/zap2docker-stable'
  #         target: ${{ env.TARGET }}
  #         rules_file_name: '.zap/rules.tsv'
  #         cmd_options: '-a'
