name: Testing 


 
on: 
 push:
  branches: 
    - master
 pull_request:
  branches: 
    - master

jobs:
 job1:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    python-version: [3.8]
    go-version: [1.13.1]
    php-version: [7.4]
  steps:

# Checking out gitGraber repo
   - name: Check out github.com/hisxo/gitGraber
     if: env.RUN_GITGRABBER == true
     uses: actions/checkout@master
     with:
       repository: hisxo/gitGraber
       path: ${{ env.GIT_GRABER }}






# installing dependecies for hisxo/gitGraber tools
   - name: installing dependecies for hisxo/gitGraber
     if: env.RUN_GITGRABBER == true
     run: |
       cd ${{ github.workspace }}/${{ env.GIT_GRABER }}
       chmod +x *
       pip3 install -r requirements.txt



# copy config.py to  gitgrabber repo       
   - name : copy config.py from main repo to gitgrabber
     if: env.RUN_GITGRABBER == true
     run : |
      cp -var ${{ github.workspace }}/config.py ${{ env.GIT_GRABER }}/   
      

        
