name: Testing 

env:
 TARGET: bugcrowd.com
 BOUNTY_STRIKE_PATH : strike 
 
on: push

jobs:
 download_others_repo:
  name: OpenRedireX - Asynchronous Open redirect Fuzzer for Humans
  
  runs-on: [ubuntu-latest]
  strategy:
   matrix:
    python-version: [3.8]
  steps:
   - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v1
     with:
        python-version: ${{ matrix.python-version }}
   

   - name : checkout https://github.com/BountyStrike/Bountystrike-sh
     uses : action/checkout@v2
     with : 
       repository : BountyStrike/Bountystrike-sh
       path :  ${{ env.BOUNTY_STRIKE_PATH }}


   - name : installing tools
     run : |
       cd ${{ github.workspace }}/${{ env.BOUNTY_STRIKE_PATH }}
       bstrike.sh install  

   - name : Run pipeline on ${{ env.TARGET }}
     run : |
       cd ${{ github.workspace }}/${{ env.BOUNTY_STRIKE_PATH }}
       bstrike.sh run Bugcrowd ${{ env.TARGET }}   
  

        
