name: Test site for publicly known js vulnerabilities

on: push
env:
 TARGET: https://hackerone.com 
jobs:
  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test for public javascript library vulnerabilities 
  #       uses: lirantal/is-website-vulnerable@master
  #       with:
  #         scan-url: ${{ env.TARGET }}
  # zap_scan:
  #   runs-on: ubuntu-latest
  #   name: Scan the webapplication
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: master
  #     - name: ZAP Scan
  #       uses: zaproxy/action-baseline@v0.2.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         docker_name: 'owasp/zap2docker-stable'
  #         target: ${{ env.TARGET }}
  #         rules_file_name: '.zap/rules.tsv'
  #         cmd_options: '-a'
